// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"xy_cms/internal/dal/gen_model"
)

func newCategory(db *gorm.DB, opts ...gen.DOOption) category {
	_category := category{}

	_category.categoryDo.UseDB(db, opts...)
	_category.categoryDo.UseModel(&gen_model.Category{})

	tableName := _category.categoryDo.TableName()
	_category.ALL = field.NewAsterisk(tableName)
	_category.ID = field.NewInt64(tableName, "id")
	_category.Model = field.NewString(tableName, "model")
	_category.Type = field.NewBool(tableName, "type")
	_category.ModelID = field.NewInt32(tableName, "model_id")
	_category.ParentID = field.NewInt32(tableName, "parent_id")
	_category.CatName = field.NewString(tableName, "cat_name")
	_category.CatDir = field.NewString(tableName, "cat_dir")
	_category.Thumb = field.NewString(tableName, "thumb")
	_category.URL = field.NewString(tableName, "url")
	_category.Sort = field.NewInt32(tableName, "sort")
	_category.IsShow = field.NewBool(tableName, "is_show")
	_category.IsMeshow = field.NewBool(tableName, "is_meshow")
	_category.IsTarget = field.NewBool(tableName, "is_target")
	_category.IsHTML = field.NewBool(tableName, "is_html")
	_category.IsLink = field.NewBool(tableName, "is_link")
	_category.TemplateCate = field.NewString(tableName, "template_cate")
	_category.TemplateList = field.NewString(tableName, "template_list")
	_category.TemplateShow = field.NewString(tableName, "template_show")
	_category.SeoTitle = field.NewString(tableName, "seo_title")
	_category.SeoKey = field.NewString(tableName, "seo_key")
	_category.SeoDes = field.NewString(tableName, "seo_des")
	_category.Power = field.NewString(tableName, "power")
	_category.URLList = field.NewInt32(tableName, "url_list")
	_category.URLShow = field.NewInt32(tableName, "url_show")

	_category.fillFieldMap()

	return _category
}

type category struct {
	categoryDo

	ALL          field.Asterisk
	ID           field.Int64
	Model        field.String
	Type         field.Bool
	ModelID      field.Int32
	ParentID     field.Int32
	CatName      field.String
	CatDir       field.String
	Thumb        field.String
	URL          field.String
	Sort         field.Int32
	IsShow       field.Bool
	IsMeshow     field.Bool
	IsTarget     field.Bool
	IsHTML       field.Bool
	IsLink       field.Bool
	TemplateCate field.String
	TemplateList field.String
	TemplateShow field.String
	SeoTitle     field.String
	SeoKey       field.String
	SeoDes       field.String
	Power        field.String
	URLList      field.Int32
	URLShow      field.Int32

	fieldMap map[string]field.Expr
}

func (c category) Table(newTableName string) *category {
	c.categoryDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c category) As(alias string) *category {
	c.categoryDo.DO = *(c.categoryDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *category) updateTableName(table string) *category {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Model = field.NewString(table, "model")
	c.Type = field.NewBool(table, "type")
	c.ModelID = field.NewInt32(table, "model_id")
	c.ParentID = field.NewInt32(table, "parent_id")
	c.CatName = field.NewString(table, "cat_name")
	c.CatDir = field.NewString(table, "cat_dir")
	c.Thumb = field.NewString(table, "thumb")
	c.URL = field.NewString(table, "url")
	c.Sort = field.NewInt32(table, "sort")
	c.IsShow = field.NewBool(table, "is_show")
	c.IsMeshow = field.NewBool(table, "is_meshow")
	c.IsTarget = field.NewBool(table, "is_target")
	c.IsHTML = field.NewBool(table, "is_html")
	c.IsLink = field.NewBool(table, "is_link")
	c.TemplateCate = field.NewString(table, "template_cate")
	c.TemplateList = field.NewString(table, "template_list")
	c.TemplateShow = field.NewString(table, "template_show")
	c.SeoTitle = field.NewString(table, "seo_title")
	c.SeoKey = field.NewString(table, "seo_key")
	c.SeoDes = field.NewString(table, "seo_des")
	c.Power = field.NewString(table, "power")
	c.URLList = field.NewInt32(table, "url_list")
	c.URLShow = field.NewInt32(table, "url_show")

	c.fillFieldMap()

	return c
}

func (c *category) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *category) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 24)
	c.fieldMap["id"] = c.ID
	c.fieldMap["model"] = c.Model
	c.fieldMap["type"] = c.Type
	c.fieldMap["model_id"] = c.ModelID
	c.fieldMap["parent_id"] = c.ParentID
	c.fieldMap["cat_name"] = c.CatName
	c.fieldMap["cat_dir"] = c.CatDir
	c.fieldMap["thumb"] = c.Thumb
	c.fieldMap["url"] = c.URL
	c.fieldMap["sort"] = c.Sort
	c.fieldMap["is_show"] = c.IsShow
	c.fieldMap["is_meshow"] = c.IsMeshow
	c.fieldMap["is_target"] = c.IsTarget
	c.fieldMap["is_html"] = c.IsHTML
	c.fieldMap["is_link"] = c.IsLink
	c.fieldMap["template_cate"] = c.TemplateCate
	c.fieldMap["template_list"] = c.TemplateList
	c.fieldMap["template_show"] = c.TemplateShow
	c.fieldMap["seo_title"] = c.SeoTitle
	c.fieldMap["seo_key"] = c.SeoKey
	c.fieldMap["seo_des"] = c.SeoDes
	c.fieldMap["power"] = c.Power
	c.fieldMap["url_list"] = c.URLList
	c.fieldMap["url_show"] = c.URLShow
}

func (c category) clone(db *gorm.DB) category {
	c.categoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c category) replaceDB(db *gorm.DB) category {
	c.categoryDo.ReplaceDB(db)
	return c
}

type categoryDo struct{ gen.DO }

type ICategoryDo interface {
	gen.SubQuery
	Debug() ICategoryDo
	WithContext(ctx context.Context) ICategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICategoryDo
	WriteDB() ICategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICategoryDo
	Not(conds ...gen.Condition) ICategoryDo
	Or(conds ...gen.Condition) ICategoryDo
	Select(conds ...field.Expr) ICategoryDo
	Where(conds ...gen.Condition) ICategoryDo
	Order(conds ...field.Expr) ICategoryDo
	Distinct(cols ...field.Expr) ICategoryDo
	Omit(cols ...field.Expr) ICategoryDo
	Join(table schema.Tabler, on ...field.Expr) ICategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICategoryDo
	Group(cols ...field.Expr) ICategoryDo
	Having(conds ...gen.Condition) ICategoryDo
	Limit(limit int) ICategoryDo
	Offset(offset int) ICategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICategoryDo
	Unscoped() ICategoryDo
	Create(values ...*gen_model.Category) error
	CreateInBatches(values []*gen_model.Category, batchSize int) error
	Save(values ...*gen_model.Category) error
	First() (*gen_model.Category, error)
	Take() (*gen_model.Category, error)
	Last() (*gen_model.Category, error)
	Find() ([]*gen_model.Category, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.Category, err error)
	FindInBatches(result *[]*gen_model.Category, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gen_model.Category) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICategoryDo
	Assign(attrs ...field.AssignExpr) ICategoryDo
	Joins(fields ...field.RelationField) ICategoryDo
	Preload(fields ...field.RelationField) ICategoryDo
	FirstOrInit() (*gen_model.Category, error)
	FirstOrCreate() (*gen_model.Category, error)
	FindByPage(offset int, limit int) (result []*gen_model.Category, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c categoryDo) Debug() ICategoryDo {
	return c.withDO(c.DO.Debug())
}

func (c categoryDo) WithContext(ctx context.Context) ICategoryDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c categoryDo) ReadDB() ICategoryDo {
	return c.Clauses(dbresolver.Read)
}

func (c categoryDo) WriteDB() ICategoryDo {
	return c.Clauses(dbresolver.Write)
}

func (c categoryDo) Session(config *gorm.Session) ICategoryDo {
	return c.withDO(c.DO.Session(config))
}

func (c categoryDo) Clauses(conds ...clause.Expression) ICategoryDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c categoryDo) Returning(value interface{}, columns ...string) ICategoryDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c categoryDo) Not(conds ...gen.Condition) ICategoryDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c categoryDo) Or(conds ...gen.Condition) ICategoryDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c categoryDo) Select(conds ...field.Expr) ICategoryDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c categoryDo) Where(conds ...gen.Condition) ICategoryDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c categoryDo) Order(conds ...field.Expr) ICategoryDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c categoryDo) Distinct(cols ...field.Expr) ICategoryDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c categoryDo) Omit(cols ...field.Expr) ICategoryDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c categoryDo) Join(table schema.Tabler, on ...field.Expr) ICategoryDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c categoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICategoryDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c categoryDo) RightJoin(table schema.Tabler, on ...field.Expr) ICategoryDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c categoryDo) Group(cols ...field.Expr) ICategoryDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c categoryDo) Having(conds ...gen.Condition) ICategoryDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c categoryDo) Limit(limit int) ICategoryDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c categoryDo) Offset(offset int) ICategoryDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c categoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICategoryDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c categoryDo) Unscoped() ICategoryDo {
	return c.withDO(c.DO.Unscoped())
}

func (c categoryDo) Create(values ...*gen_model.Category) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c categoryDo) CreateInBatches(values []*gen_model.Category, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c categoryDo) Save(values ...*gen_model.Category) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c categoryDo) First() (*gen_model.Category, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.Category), nil
	}
}

func (c categoryDo) Take() (*gen_model.Category, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.Category), nil
	}
}

func (c categoryDo) Last() (*gen_model.Category, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.Category), nil
	}
}

func (c categoryDo) Find() ([]*gen_model.Category, error) {
	result, err := c.DO.Find()
	return result.([]*gen_model.Category), err
}

func (c categoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.Category, err error) {
	buf := make([]*gen_model.Category, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c categoryDo) FindInBatches(result *[]*gen_model.Category, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c categoryDo) Attrs(attrs ...field.AssignExpr) ICategoryDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c categoryDo) Assign(attrs ...field.AssignExpr) ICategoryDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c categoryDo) Joins(fields ...field.RelationField) ICategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c categoryDo) Preload(fields ...field.RelationField) ICategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c categoryDo) FirstOrInit() (*gen_model.Category, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.Category), nil
	}
}

func (c categoryDo) FirstOrCreate() (*gen_model.Category, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.Category), nil
	}
}

func (c categoryDo) FindByPage(offset int, limit int) (result []*gen_model.Category, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c categoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c categoryDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c categoryDo) Delete(models ...*gen_model.Category) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *categoryDo) withDO(do gen.Dao) *categoryDo {
	c.DO = *do.(*gen.DO)
	return c
}
