// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"xy_cms/internal/handler/v1"
	"xy_cms/internal/service"
)

// Injectors from wire.go:

func NewHandler() (*Handler, error) {
	iCategoryService := service.NewCategoryServiceImpl()
	categoryHandler := v1.NewCategoryHandler(iCategoryService)
	handler := &Handler{
		Category: categoryHandler,
	}
	return handler, nil
}
