// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"xy_cms/internal/controller/admin"
	"xy_cms/internal/service"
)

// Injectors from wire.go:

func InitializeCategoryControllerV2() admin.CategoryControllerV2 {
	categoryServiceInterface := service.NewCategoryServiceImpl()
	categoryControllerV2 := admin.NewCategoryControllerV2(categoryServiceInterface)
	return categoryControllerV2
}
